name: random_digit
description: Random digit generation
version: 1.0.0
homepage: https://www.leventkantaroglu.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
